package com.mygdx.hastypastry.models;

import com.badlogic.gdx.scenes.scene2d.ui.Container;
import com.mygdx.hastypastry.ui.StyledTextButton;

import java.util.List;

/**
 * A model describing a user for storage in the database.
 * FBID is DAtabase ID, and is a random string generated by the
 * Firebase upon request by the FBDatabase class
 */
public class User {
    private String FBID;
    private String name;
    private String status;
    private Match challenge; // Null if you are the challenger.
    private List<List<String>> drawing;
    private Container<StyledTextButton> userUI;

    // Default constructor required for calls to DataSnapshot.getValue(User.class)
    public User() {};

    public User(String name) {
        this.name = name;
        status = "ready";
    }

    public String getName() {
        return name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Match getChallenge() {
        return challenge;
    }

    public void setChallenge(Match challenge) {
        this.challenge = challenge;
    }

    public String getFBID() {
        return FBID;
    }

    public void setFBID(String FBID) {
        this.FBID = FBID;
    }

    protected Container<StyledTextButton> getUserUI() {
        return userUI;
    }

    public void setUserUI(Container<StyledTextButton> userUI) {
        this.userUI = userUI;
    }
}
